package main

import (
	"bytes"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer/html"
)

// md is the renderer used by the docs site builder. GFM covers the
// extensions the upstream docs already rely on (tables, autolinks, task
// lists, strikethrough). Raw inline HTML is permitted via WithUnsafe so
// the upstream docs can keep their existing <details> and other GPT-flavoured
// elements; this is build time, not runtime.
var md = goldmark.New(
	goldmark.WithExtensions(extension.GFM),
	goldmark.WithParserOptions(parser.WithAutoHeadingID()),
	goldmark.WithRendererOptions(html.WithUnsafe()),
)

// renderMarkdown converts GitHub-flavoured markdown to HTML. Callers are
// expected to strip YAML front matter before calling this; the heading
// auto-ID set generated by Goldmark is later augmented with explicit
// anchors by sectionSlugs.
func renderMarkdown(src []byte) ([]byte, error) {
	var buf bytes.Buffer
	if err := md.Convert(src, &buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
