#!/bin/sh
# Regenerate docs/compat/matrix.md from the local results
# (harness/observations/local) and every live observation directory listed
# in harness/observations/ORDER, oldest first; later runs override earlier
# ones for the same case.
#
#   scripts/matrix.sh                 # use the committed local results
#   scripts/matrix.sh --refresh-local # re-run every local case (--slow) first
set -eu
cd "$(dirname "$0")/.."
if [ "${1:-}" = "--refresh-local" ]; then
  tmp=$(mktemp -d)
  go run ./harness/cmd/harness run --slow --observations "$tmp" || true
  rm -rf harness/observations/local && mv "$tmp" harness/observations/local
fi
live=$(sed -e '/^#/d' -e '/^$/d' -e 's|^|harness/observations/|' harness/observations/ORDER | paste -sd, -)
{
  echo "# Compatibility matrix"
  echo
  echo "Generated by \`scripts/matrix.sh\` on $(date +%F) from the local results and the live observation directories in \`harness/observations/ORDER\` (later runs override earlier ones)."
  echo
  go run ./harness/cmd/harness matrix --live-observations "$live"
} > docs/compat/matrix.md
grep '^| \*\*Total' docs/compat/matrix.md
