#!/bin/sh
# Re-measure performance and update the generated block of
# docs/compat/performance.md. Run on an otherwise idle machine; the numbers
# are only comparable on the same hardware.
#
#   scripts/perf.sh [-duration 5s] [-subscribers 200]
set -eu
cd "$(dirname "$0")/.."
out=$(mktemp)
trap 'rm -f "$out"' EXIT
go run ./tools/loadtest "$@" > "$out"
cat "$out"
python3 - "$out" <<'PY'
import sys, re, datetime, subprocess
res = open(sys.argv[1]).read().strip()
p = "docs/compat/performance.md"
s = open(p).read()
begin = "<!-- perf:begin (generated by scripts/perf.sh) -->"
s = re.sub(re.escape(begin) + r".*?<!-- perf:end -->", begin + "\n" + res + "\n<!-- perf:end -->", s, flags=re.S)
commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()
s = re.sub(r"last run [^.]*\.", f"last run {datetime.date.today()}, commit {commit}.", s, count=1)
open(p, "w").write(s)
PY
echo "updated docs/compat/performance.md"
